### ISSUE TITLE
Normalize / jQuery ?

### ISSUE THREAD

**Issue by starckio** [99kocms/99ko#1]
Pourquoi obliger l'utilisation de normalize et jQuery ?
(de même pour certain CSS's)

Obliger de supprimer les liens directement dans les fichier pour un themes personnalisé pour un client… C'est pas cool car refaire la même manip après une mise à jour.

En tant que concepteur designer, j'aimerais avoir plus de liberté de personnalisation avec les futur mises à jour. Ça m'encouragerais aussi pour sortir des themes assez custom pour la communauté.

**Comment by j84** [comment]
Ce choix permet, pour jQuery, de concevoir des plugins pouvant l'utiliser sans se soucier de son intégration ou de dépendre d'un autre plugin qui permettrait d'intégrer jQuery au thème. Le plugin Galerie par exemple l'utilise. jQuery et Normalize étant utilisés dans l'administration, il me semblait logique de les intégrer aux thèmes par défaut.

Par contre lors de la conception d'un thème il est possible de désactiver ces deux composants de façon propre en utilisant la surcharge de la classe show qui est responsable de l'affichage d'un thème. Il faut pour cela réécrire deux méthodes de cette classe au sein du fichier functions.php du thème, via des fonctions.

Par exemple la méthode linkTags (voir aussi scriptTags) permet d'associer Normalize au thème, mais en créant cette fonction (au seins du fichier functions.php du thème), qui n'ai autre que la copie de la méthode linksTags de la classe show avec une partie du code commenté, on désactive Normalize dans le thème : 

`
function linkTags(){
    $core = core::getInstance();
    $pluginsManager = pluginsManager::getInstance();
    /*foreach($core->getCss() as $k=>$v){
        echo '<link href="'.$v.'" rel="stylesheet" type="text/css" />';
    }*/
    foreach($pluginsManager->getPlugins() as $k=>$plugin) if($plugin->getConfigval('activate') == 1){
        if(ROOT == './' && $plugin->getConfigVal('activate') && $plugin->getPublicCssFile()) echo '<link href="'.$plugin->getPublicCssFile().'" rel="stylesheet" type="text/css" />';
        elseif(ROOT == '../' && $plugin->getConfigVal('activate') && $plugin->getAdminCssFile()) echo '<link href="'.$plugin->getAdminCssFile().'" rel="stylesheet" type="text/css" />';
    }
    if(ROOT == './') echo '<link href="'.$core->getConfigVal('siteUrl').'/'.'theme/'.$core->getConfigVal('theme').'/styles.css" rel="stylesheet" type="text/css" />';
}`
