### ISSUE TITLE
Anchor issue

### ISSUE THREAD

**Issue by gdw96** [99kocms/99ko#11]
Bonjour,

J'ai constaté un problème avec les ancres dans les pages. Avec l'éditeur intégré, j'ai mis des ancres pointant vers les différentes titres de ma page. Côté HTML tout est parfait, que ce soit dans l'éditeur ou dans la page (j'ai bien un lien qui ressemble à cela : `<a href="#ancre">Ancre</a>`).

Sauf que si je clique dessus, je suis dirigé vers la racine du site (par exemple : au lieu d'avoir `https://monsite.fr/page/ma-page-1.html#ancre`, j'ai `https://monsite.fr/#ancre`). J'ai ce problème quel que soit le navigateur utilisé : Firefox, Firefox Quantum, New Edge ou Chromium. J'ai essayé de modifier les règles du .htaccess sans succès.

Une solution possible serait de mettre le lien absolu, mais le problème, c'est que si le titre de la page change, plus rien ne fonctionne.

N'ayant trouvé aucune solution pour l'instant, je me permets de faire appel à l'intelligence collective. :-)

**Comment by j84** [comment]
Je pense que ça rejoint ceci : https://github.com/99kocms/99ko-v4-v5/pull/8

**Comment by gdw96** [comment]
Malheureusement, non, les problèmes ne sont pas liés.

Que mon ancre soit écrite en dur dans le code HTML de la page (thème) ou par TinyMCE, le problème est exactement le même. Dans le code source de la page du navigateur, j'ai bien une ancre parfaitement normale : `<a href="#ancre">Anchor test</a>`

Et pourtant (et quelque soit le navigateur utilisé) si je mets la souris sur le lien, le navigateur m'affiche : `https://monsite.fr/#ancre` au lieu de `https://monsite.fr/page/ma-page-1.html#ancre` ou encore `https://monsite.fr/index.php?p=page&url=ma-page&id=1#ancre`.

En revanche, si j'écris l'URL absolue (avec l'ancre) ça fonctionne. Le problème étant que s'il y a le moindre changement dans le nom de la page, plus rien ne fonctionne et devoir changer tous les liens de toutes les ancres d'une page au moindre changement est une source d'erreur potentiel incroyable.

Et cela, quelque soit le navigateur web, quel que soit l’appareil utilisé (Android, Windows, ou un Linux). En y réfléchissant un peu plus je dois avoir un problème de configuration d'Apache2 ou un problème dans le htaccess ? (cependant je n'y ai pas touché, enfin mes tentatives de résolution ayant échoués, j'ai remis la configuration du htaccess par défaut). Et honnêtement, je sèche sur ce problème pour l'instant.

J'ai bien vu ce genre de choses, mais ça ne change rien du tout chez moi : https://helpx.adobe.com/ch_fr/experience-manager/kb/Apache-RewriteRule-with-anchor-not-redirecting-properly-AEM-Dispatcher.html

Edit : Je reviens sur ce que j'ai dit, ce problème ne vient pas de ma configuration. Pour preuve, j'ai essayé avec le PHP Built-In Web Server sur différents appareilles Windows et Linux. J'ai essayé sur différents VPS et enfin, j'ai essayé sur un hébergement OVH (tout ce qu'il y a de plus classique). Quelle que soit la configuration, j'ai exactement le même problème. Pour aller plus loin, j'ai également essayé d'autres sites que j'ai réalisés sur exactement les mêmes configurations. Que ce soit avec le framework Symfony ou From-Scratch tous leurs ancres fonctionnes correctement et comme elle devraient sauf avec 99ko.

**Comment by MaxenceCauderlier** [comment]
Hello, 
Je pense que ça vient de la balise <base bref.... Qui est incompatible avec les ancres. 

Dans un des scripts, essaye d'ajouter ce code js :

`$(document).ready(function() {
   var pathname = window.location.href.split('#')[0];
    $('a[href^="#"]').each(function() {
        var $this = $(this),
            link = $this.attr('href');
        $this.attr('href', pathname + link);
    });
});`

Désolé suis sur téléphone, je préciserai si besoin.

**Comment by gdw96** [comment]
Hey,

Bien joué ! D'autant plus sur smartphone. Ah, je savais que l'intelligence collective allait fonctionner. Tu viens de gagner une médaille.

J'ignorais que 99ko utilisait la balise base (à vrai dire, ce n'est pas une balise que l'on croise très souvent). Ok donc j'ai tout compris. La balise "base" détermine en gros l'url de la "base" du site. Par conséquent toutes les URL relatives se base dessus. Donc lorsque je fais une ancre interne à la page (qui est une URL relative), il se base sur l'URL de base et ajoute l'ancre. Voilà pourquoi je suis redirigé forcément à la base du site. ;-)

Par conséquent ce problème doit être le même chez tout le monde..

Du coup, ton petit code JS récupère toutes les URL commençant par une ancre ("#") et les ré-écrit à la volée en y ajoutant l'URL de la page courante en question. Ce n'est pas idéal mais ça fonctionne.

**Comment by MaxenceCauderlier** [comment]
C'est exactement cela.
En effet, ce n'est pas le top, mais ça fonctionne en attendant une solution viable. À en croire la toile il n'existe pas de solution sans Javascript. 
Il faut supprimer la balise <base>, ou ne pas supporter les ancres...

**Comment by gdw96** [comment]
À moins de remplacer la balise par un système complet de génération de lien interne au CMS. Mais ça complique largement les choses, ça demande d'adapter tout le code (également de TinyMCE et des autres plugin, etc.), bref, ça s'éloigne de la philosophie de 99ko, c'est un peu overkill MDR, mais c'est tout à fait possible.

**Comment by MaxenceCauderlier** [comment]
Non pas overkill du tout, il faut juste virer la balise base et ajouter le préfixe du site en php à chaque URL qui est gérée par le code. 
Pour les contenus, TinyMce va faire le taf tout seul avec les URL relatives, du moins je crois. 

J'essaye actuellement d'aider Jon dans ce projet, mais la vie IRL, tout comme lui je crois, est très prenante en ce moment. Mais une nouvelle version devrait sortir sous peu, en espérant qu'on arrive à dégager du temps pour cela.

**Comment by gdw96** [comment]
Un très beau projet. Je l'ai découvert dans ces premières version, peut-être même la première. Ensuite j'ai eu pas mal de taf, donc je l'ai complètement zappé. Et là, ayant eu une toute petite mission, je me suis souvenu de 99ko, j'avais justement besoin d'un base très simple sur laquelle m'appuyer et modifier. Et il a bien changé depuis les années ! Ça fait plaisir, j'ai eu peur qu'il ai fini par être délaissé et abandonné.
