### ISSUE TITLE
Problème de surcharge de méthodes de la class "show".

### ISSUE THREAD

**Issue by gdw96** [99kocms/99ko#12]
C'est génial que vous ayez pensé à mettre en place un système de surcharge de la classe `show` malheureusement il y a quelques erreurs.

Un exemple :
`
    public static function msg($msg) {
        if (function_exists('msg')) call_user_func('msg');
        [...]
    }
`

Ici, vous ne passez par le paramètre `$msg` à la fonction surchargée. Il faudrait faire ainsi pour que ça fonctionne :
`
    public static function msg($msg) {
        if (function_exists('msg')) call_user_func('msg', $msg);    <-- Ajout du paramètre $msg à l'appel de la fonction surchargée.
        [...]
    }
`

Il doit certainement y avoir d'autres coquilles ainsi, mais je n'ai pas regardé honnêtement.

https://www.php.net/manual/fr/function.call-user-func

Edit : En effet, l'erreur est présente sur toutes les fonctions avec paramètres : `mainTitle`, `mainNavigation`, `theme`, etc. (et peut-être ailleurs dans le CMS, je l'ignore).

Edit : Edit : La surcharge de la méthode `mainNavigation` va aussi poser problème même avec la correction ci-dessus parce que le `echo $data;` est hors de la condition, hors du `else`. Il faut aussi impérativement déplacer ce `echo` à l'intérieur du `else`.

**Comment by j84** [comment]
Merci, j'apporte la correction sur la branche dev
